model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ""
  - model_name: claude-4
    litellm_params:
      model: "claude-opus-4-20250514"
      api_key: ""

# How to use it
# litellm --config config.yaml
